// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI8VvgGcGOR_k14EwL067-kwTexnIiOV0',
    appId: '1:311915419198:web:98d52f9e707b92f8d6a36f',
    messagingSenderId: '311915419198',
    projectId: 'marine-analytics-platform',
    authDomain: 'marine-analytics-platform.firebaseapp.com',
    storageBucket: 'marine-analytics-platform.firebasestorage.app',
    measurementId: 'G-NC048VS02Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbG47lUQkSUHqwsaiYCy2a7XEyw7M-mxk',
    appId: '1:311915419198:android:3d851ca60e37e22bd6a36f',
    messagingSenderId: '311915419198',
    projectId: 'marine-analytics-platform',
    storageBucket: 'marine-analytics-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3XUJ7Wa6gipFbq8b-iheU7Kcq6kVvb7U',
    appId: '1:311915419198:ios:819d123f1228c99ad6a36f',
    messagingSenderId: '311915419198',
    projectId: 'marine-analytics-platform',
    storageBucket: 'marine-analytics-platform.firebasestorage.app',
    iosBundleId: 'vn.coquan.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3XUJ7Wa6gipFbq8b-iheU7Kcq6kVvb7U',
    appId: '1:311915419198:ios:712955e65eee5140d6a36f',
    messagingSenderId: '311915419198',
    projectId: 'marine-analytics-platform',
    storageBucket: 'marine-analytics-platform.firebasestorage.app',
    iosBundleId: 'marine.analytics.platform.marineAnalyticsPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI8VvgGcGOR_k14EwL067-kwTexnIiOV0',
    appId: '1:311915419198:web:f5c0b4945cd68f47d6a36f',
    messagingSenderId: '311915419198',
    projectId: 'marine-analytics-platform',
    authDomain: 'marine-analytics-platform.firebaseapp.com',
    storageBucket: 'marine-analytics-platform.firebasestorage.app',
    measurementId: 'G-TE5CZ3DKLZ',
  );
}